[database]
# SQLAlchemy/psycopg connection URL
database_url = postgresql://mydata:mydata123@172.30.1.128:5432/mydata

[postgres]
host = 172.30.1.128
port = 5432
name = mydata
user = mydata
password = mydata123
